services:
  israeli-banks-sure-importer:
    image: tomerh2001/israeli-banks-sure-importer:latest
    container_name: israeli-banks-sure-importer
    cap_add:
      - SYS_ADMIN
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Jerusalem
      # - SCHEDULE=0 */6 * * *
      # - OUTPUT_DIRECTORY=/app/output
      # - OUTPUT_FORMAT=json-and-csv
    volumes:
      - ./config.json:/app/config.json:ro
      - ./output:/app/output
      - ./chrome-data:/app/chrome-data
